# Generated by Django 4.1.7 on 2023-03-30 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariant',
            name='by_age',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.by_age'),
        ),
    ]
