# Generated by Django 4.1.7 on 2023-04-25 05:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_offer'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='offer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.offer'),
        ),
    ]
