# Generated by Django 4.1.7 on 2023-04-29 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_category_offer_products_offer'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='specification',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
