from unicodedata import name
from django.urls import path

from admin_panel import views

urlpatterns = [
    path('login',views.adminlogin, name='adminlogin'),
    path('',views.adminpage,name='adminpage'),
    path('customers',views.customer_details,name='customer_details'),
    path('logout',views.adminlogout,name='adminlogout'),
    path('Customer-delete <int:id>',views.Customer_delete,name='Customer_delete'),
    path('customer-update <int:id>',views.customer_update,name='Customer_update'),
    path('add-customer',views.add_customer,name='add_customer'),
    path('products',views.product_details,name='product_details'),
    path('product-delete <uuid:uid>',views.product_delete,name='product_delete'),
    path('product-update <uuid:uid>',views.product_update,name='product_update'),
    path('add-product',views.add_product,name='add_product'),
    path('variants',views.variant_details,name='variant_details'),
    path('add-brands',views.add_brands,name='add_brands'),
    path('update-brands <uuid:uid>',views.brand_update,name='brand_update'),  
    path('delete-brands <uuid:uid>',views.brand_delete,name='brand_delete'), 
    path('add-colors',views.add_color,name='add_color'),
    path('update-colors <uuid:uid>',views.color_update,name='color_update'),
    path('delete-colors <uuid:uid>',views.color_delete,name='color_delete'), 
    path('add-sizes',views.add_size,name='add_size'),
    path('update-sizes <uuid:uid>',views.size_update,name='size_update'),
    path('delete-sizes <uuid:uid>',views.size_delete,name='size_delete'), 
    path('add-age',views.add_age,name='add_age'),
    path('update-age <uuid:uid>',views.age_update,name='age_update'),
    path('delete-age <uuid:uid>',views.age_delete,name='age_delete'),
    path('add-tag',views.add_tag,name='add_tag'),
    path('update-tag <uuid:uid>',views.tag_update,name='tag_update'),
    path('delete-tag <uuid:uid>',views.tag_delete,name='tag_delete'),
    path('sections',views.Sections_details,name='Sections_details'),
    path('add-sections',views.add_sections,name='add_sections'),
    path('update-sections <uuid:uid>',views.section_update,name='section_update'),  
    path('delete-sections <uuid:uid>',views.section_delete,name='section_delete'),
    path('add-subsections',views.add_subsections,name='add_subsections'),
    path('update-subsections <uuid:uid>',views.subsection_update,name='subsection_update'),  
    path('delete-subsections <uuid:uid>',views.subsection_delete,name='subsection_delete'),
    path('categories',views.Category_details,name='Category_details'),
    path('add-category',views.add_category,name='add_category'),
    path('update-category <uuid:uid>',views.category_update,name='category_update'),
    path('delete-category <uuid:uid>',views.Category_delete,name='Category_delete'),
    path('orders',views.view_all_orders,name='view_all_orders'),
    path('order-details <uuid:uid>',views.view_order_details,name='view_order_details'),
    path('coupons',views.Coupon_details,name='Coupon_details'),
    path('coupon-delete <uuid:uid>',views.coupon_delete,name='coupon_delete'),
    path('admin-profile',views.admin_profile,name='admin_profile'),
    path('admin-bank-details',views.View_BankDetails,name='admin_bank'),
    path('add-account-details',views.add_account_details,name='add_account_details'),
    path('delete-bank-account  <uuid:uid>', views.delete_account ,name='delete_account'),
    path('edit-bank-account  <uuid:uid>', views.edit_account_details ,name='edit_account'),
    path('security-settings',views.security,name='security_settings'),
    path('sales-report',views.sales_report,name='sales_report'),
    path('offers',views.Offer_details,name='Offer_details'),
    path('offer-delete <uuid:uid>',views.offer_delete,name='offer_delete'),
]
