# Generated by Django 4.1.7 on 2023-04-21 05:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin_Bank_Details',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('account_holder', models.CharField(max_length=50)),
                ('bank', models.CharField(max_length=50)),
                ('branch', models.EmailField(max_length=254)),
                ('IFSC', models.CharField(max_length=50)),
                ('account_number', models.CharField(max_length=50)),
                ('Upi', models.CharField(max_length=50)),
                ('is_default', models.BooleanField(default=False)),
                ('admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
