# Generated by Django 4.1.7 on 2023-04-25 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin_bank_details',
            name='branch',
            field=models.CharField(max_length=50),
        ),
    ]
