# Generated by Django 4.1.7 on 2023-03-31 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_cart_total_price'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
