# Generated by Django 4.1.7 on 2023-04-01 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0007_addresses_note'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addresses',
            name='type',
        ),
        migrations.AddField(
            model_name='addresses',
            name='type',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='cart.addresstype'),
            preserve_default=False,
        ),
    ]
