# Generated by Django 4.1.7 on 2023-04-01 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0008_remove_addresses_type_addresses_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addresses',
            name='type',
            field=models.CharField(choices=[('home', 'home'), ('office', 'office'), ('other', 'other')], default='home', max_length=200),
        ),
        migrations.DeleteModel(
            name='Addresstype',
        ),
    ]
