# Generated by Django 4.1.7 on 2023-04-01 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0009_alter_addresses_type_delete_addresstype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingaddress',
            name='address',
        ),
        migrations.RemoveField(
            model_name='shippingaddress',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='shippingaddress',
            name='order',
        ),
        migrations.DeleteModel(
            name='Addresses',
        ),
        migrations.DeleteModel(
            name='ShippingAddress',
        ),
    ]
