# Generated by Django 4.1.7 on 2023-04-02 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
        ('cart', '0010_remove_shippingaddress_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('COD', 'COD'), ('UPI', 'UPI'), ('Net Banking', 'Net Banking'), ('Debit/Credit cards', 'Debit/Credit cards')], default='COD', max_length=200),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='checkout.address'),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('placed', 'placed'), ('canceled', 'canceled'), ('shipped', 'shipped'), ('delivered', 'delivered')], default='pending', max_length=200),
        ),
    ]
