# Generated by Django 4.1.7 on 2023-04-04 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0015_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='canceled_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
