# Generated by Django 4.1.7 on 2023-04-11 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0017_order_returned_date_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('processed', 'processed'), ('out for shipping', 'out for shipping'), ('canceled', 'canceled'), ('shipped', 'shipped'), ('out for delivery', 'out for delivery'), ('delivered', 'delivered'), ('returned', 'returned'), ('refunded', 'refunded')], default='pending', max_length=200),
        ),
    ]
