# Generated by Django 4.1.7 on 2023-04-26 05:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_category_offer_products_offer'),
        ('cart', '0021_order_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='offer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.offer'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('COD', 'COD'), ('Razorpay', 'Razorpay'), ('Paypal', 'Paypal')], default='COD', max_length=200),
        ),
    ]
