# Generated by Django 4.1.7 on 2023-04-29 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0023_orderitem_is_offer_applied'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='offer_applied',
            field=models.BooleanField(default=False),
        ),
    ]
